name: Build & Deploy Doxygen Docs

# -------------------------------------------------
# Trigger on pushes (or PRs) to the default branch
# -------------------------------------------------
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# -------------------------------------------------
# Permissions needed for the deploy‑pages action
# -------------------------------------------------
permissions:
  contents: read          # checkout
  pages: write            # create a Pages deployment
  id-token: write         # OIDC token for auth

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # -------------------------------------------------
    # IMPORTANT: Declare the Pages environment here
    # -------------------------------------------------
    environment:
      name: github-pages          # <-- matches the environment GitHub creates for Pages
      url: ${{ steps.deploy.outputs.page_url }}   # optional, lets you reference the URL later

    steps:
      # -------------------------------------------------
      # 1️⃣ Checkout the repository
      # -------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for proper git history when publishing

      # -------------------------------------------------
      # 2️⃣ Install Doxygen + Graphviz (for diagrams)
      # -------------------------------------------------
      - name: Install Doxygen and Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      # -------------------------------------------------
      # 3️⃣ Build the documentation
      # -------------------------------------------------
      - name: Build Doxygen docs
        run: |
          echo "===== Doxyfile ====="
          cat Doxyfile
          echo "===================="
          doxygen Doxyfile

      # -------------------------------------------------
      # 4️⃣ Debug: list generated files (helps catch path issues)
      # -------------------------------------------------
      - name: List generated files (debug)
        run: |
          echo "=== Repository tree after Doxygen ==="
          ls -R .
          echo "Looking for ./docs/html ..."
          if [ -d "./docs/html" ]; then
            echo "✅ Found ./docs/html"
          else
            echo "❌ ./docs/html NOT found"
            exit 1
          fi

      # -------------------------------------------------
      # 5️⃣ Upload the HTML artifact (point to docs/html)
      # -------------------------------------------------
      - name: Upload documentation artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/html          # <-- your actual output folder
          name: github-pages
          retention-days: 1

      # -------------------------------------------------
      # 6️⃣ Deploy to GitHub Pages
      # -------------------------------------------------
      - name: Deploy to GitHub Pages
        id: deploy                 # gives us the output `page_url` if we need it
        uses: actions/deploy-pages@v4